version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_DB: supportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2002
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-app
    depends_on:
      - db
    ports:
      - "8190:8190"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/supportdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2002
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    command: ["java", "-jar", "Parcial3-0.0.1-SNAPSHOT.jar"]

volumes:
  db_data: