version: '3.8'

services:
  db:
    image: postgres:16
    container_name: parcial_pg_db
    restart: always
    environment:
      POSTGRES_DB: suportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2002
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: parcial_app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/suportdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2002
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

volumes:
  db_data:
